const SongsActionType = {
  FETCH_ALL_SONGS: "FETCH_ALL_SONGS",
  FETCH_SONG: "FETCH_SONG",
  FETCH_CURRENT_PLAYING_SONG: "FETCH_CURRENT_PLAYING_SONG",
  ADD_SONG: "ADD_SONG",
  RESET_CURRENT_PLAYING_SONG: "RESET_CURRENT_PLAYING_SONG",
};

export default SongsActionType;
