const UserActionType = {
    FETCHING_USER_PROFILE: "FETCHING_USER_PROFILE", 
    FETCHING_SPOTIFY_OAUTH: "FETCHING_SPOTIFY_OAUTH",
    REFRESH_TOKEN: "REFRESH_TOKEN",
    FETCHING_UPDATEDAT: "FETCHING_UPDATEDAT",
};

export default UserActionType;