const PlaybacksActionType = {
  FETCH_ALL_PLAYBACKS: "FETCH_ALL_PLAYBACKS",
  FETCH_PLAYBACK: "FETCH_PLAYBACK",
  CREATE_PLAYBACK: "CREATE_PLAYBACK",
  FETCH_PERSONAL_PLAYBACKS: "FETCH_PERSONAL_PLAYBACKS",
};

export default PlaybacksActionType;
