const PlaybacksActionType = {
  FETCH_ALL_PLAYBACKS: "FETCH_ALL_PLAYBACKS",
  FETCH_PLAYBACK: "FETCH_PLAYBACK",
  CREATE_PLAYBACK: "CREATE_PLAYBACK",
  FETCH_PERSONAL_PLAYBACKS: "FETCH_PERSONAL_PLAYBACKS",
  FETCH_PLAYBACK_STATE: "FETCH_PLAYBACK_STATE",
  FETCH_ACTIVE_PLAYBACKS: "FETCH_ACTIVE_PLAYBACKS",
  REMOVE_ACTIVE_PLAYBACKS_FOR_USER: "REMOVE_ACTIVE_PLAYBACKS_FOR_USER",
};

export default PlaybacksActionType;
